Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2021-08, with the labels that each got.

#140 Bugfix/management resource group custom name
  modules/management/locals.tf
Labels: bug

#137 Updating mgmt pages, sidebar, and upgrade to 0.4.0 links
  .github/workflows/wiki-sync.yml
  .gitignore
  docs/wiki/Examples.md
  docs/wiki/Home.md
  docs/wiki/User-Guide.md
  docs/wiki/[Examples]-Deploy-Custom-Management-Landing-Zone.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[User-Guide]-Module-Variables.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/examples-deploy-management-resources.png
Labels: documentation

#143 Fix images in README.md and azp-spn-generator.sh error
  README.md
  tests/scripts/azp-spn-generator.sh
Labels: bug, documentation

#144 Fix Provider Declaration
  docs/wiki/[User-Guide]-Provider-Configuration.md
Labels: bug, documentation
