Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2021-10, with the labels that each got.

#177 Update connectivity content in Wiki
  README.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[Examples]-Override-Module-Role-Assignments.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  docs/wiki/media/examples-deploy-connectivity-core.png
  docs/wiki/media/examples-deploy-connectivity-custom-core.png
  docs/wiki/media/examples-deploy-connectivity-custom-rsg-myorg-connectivity-northeurope.png
  docs/wiki/media/examples-deploy-connectivity-custom-rsg-myorg-connectivity-westeurope.png
  docs/wiki/media/examples-deploy-connectivity-custom-rsg-myorg-ddos.png
  docs/wiki/media/examples-deploy-connectivity-custom-rsg-myorg-dns.png
  docs/wiki/media/examples-deploy-connectivity-custom-rsgs.png
  docs/wiki/media/examples-deploy-connectivity-dns-rsg.png
  docs/wiki/media/examples-deploy-connectivity-rsg.png
  docs/wiki/media/examples-deploy-connectivity-rsgs.png
  modules/connectivity/locals.tf
Labels: bug, documentation

#178 Patch library update
  .github/scripts/Invoke-LibraryUpdate.ps1
Labels: bug

#181 Update [User-Guide]-Archetype-Definitions.md
  docs/wiki/[User-Guide]-Archetype-Definitions.md
Labels: documentation
