Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2021-12, with the labels that each got.

#231 Add `required_version` for Terraform
  terraform.tf
Labels: enhancement

#234 Add `configure_management_resources` docs
  docs/wiki/[Variables]-configure_management_resources.md
  docs/wiki/[Variables]-configure_management_resources_advanced.md
Labels: documentation

#242 Update validation to fix #241
  modules/archetypes/variables.tf
Labels: bug

#247 Update ready for release `v1.1.1`
  README.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Identity-Resources.md
  docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[Examples]-Override-Module-Role-Assignments.md
  docs/wiki/[User-Guide]-Getting-Started.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  locals.tf
Labels: documentation
