Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2021-05, with the labels that each got.

#84 issue 48 hotfix
  locals.policy_assignments.tf
Labels: bug

#80 Update test framework
  .github/workflows/code-review.yml
  modules/archetypes/locals.policy_assignments.tf
  modules/management/locals.tf
  tests/deployment/lib/archetype_definitions/archetype_definition_customer_root.json
  tests/deployment/lib/archetype_extensions/archetype_extension_es_root.json
  tests/deployment/main.tf
  tests/deployment/provider.tf
  tests/deployment/resources.tf
  tests/pipelines/templates/tests-common.yml
  tests/scripts/azp-strategy.ps1
  tests/scripts/tf-apply.sh
  tests/scripts/tf-create-spn.sh
  tests/scripts/tf-plan.sh
  tests/scripts/tf-prepare.sh
Labels: enhancement

#86 Patch issue 85
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_defender.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azactivity_log.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_log_analytics.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_lx_arc_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vm_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vmss_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_ws_arc_monitoring.tmpl.json
  modules/management/locals.tf
Labels: bug

#87 Update for release v0.3.0
  README.md
Labels: documentation

#94 Update docs for release v0.3.1
  README.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
Labels: documentation

#100 Update `retention_in_days` config to fix #99
  modules/management/locals.tf
  modules/management/outputs.tf
  modules/management/variables.tf
Labels: bug

#103 Add "Identity" module
  locals.management_groups.tf
  locals.tf
  main.tf
  modules/archetypes/lib/archetype_definitions/archetype_definition_es_identity.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_public_ip.tmpl.json
  modules/identity/locals.tf
  modules/identity/main.tf
  modules/identity/outputs.tf
  modules/identity/variables.tf
  modules/management/variables.tf
  variables.tf
Labels: enhancement

#106 Update test framework
  Makefile
  tests/pipelines/spn-generator.yml
  tests/pipelines/tests-e2e.yml
  tests/pipelines/tests-unit.yml
  tests/scripts/azp-spn-generator.sh
Labels: enhancement

#98 Fix for GitHub issue 97
  locals.management_groups.tf
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_appgw_without_waf.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_http_ingress_aks.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_ip_forwarding.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_priv_containers_aks.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_priv_escalation_aks.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_rdp_from_internet.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_resource_locations.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_resource_types.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_rsg_locations.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_storage_http.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_subnet_without_nsg.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_subnet_without_udr.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_aks_policy.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_defender.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_azactivity_log.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_log_analytics.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_lx_arc_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_resource_diag.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_sql_db_auditing.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_sql_security.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vm_backup.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vm_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_vmss_monitoring.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_ws_arc_monitoring.tmpl.json
  modules/archetypes/locals.policy_assignments.tf
Labels: bug, do not merge

#107 Improvements to management logic
  locals.management_groups.tf
  modules/management/locals.tf
  tests/deployment/locals.core.tf
  tests/deployment/locals.management.tf
  tests/deployment/main.tf
  tests/deployment/variables.tf
  tests/scripts/tf-plan.sh
Labels: enhancement

#108 Enable management resource testing
  tests/deployment/main.tf
  tests/pipelines/templates/tests-strategy.yml
  tests/scripts/azp-spn-generator.sh
  tests/scripts/azp-strategy.ps1
  tests/scripts/tf-destroy.sh
  tests/scripts/tf-prepare.sh
Labels: enhancement

#110 Update version on Getting Started page to 0.3.1
  docs/wiki/[User-Guide]-Getting-Started.md
Labels: documentation

#112 Update for release v0.3.2
  README.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[User-Guide]-Getting-Started.md
  tests/scripts/azp-strategy.ps1
Labels: documentation
