Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2021-03, with the labels that each got.

#49 Prepare for release 0.1.0
  .github/workflows/update-policy.yml
  CONTRIBUTING.md
  README.md
  media/terraform-caf-enterprise-scale-overview.png
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_resource_locations.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_rsg_locations.tmpl.json
  modules/archetypes/lib/role_definitions/role_definition_es_network_subnet_contributor.tmpl.json
  resources.role_definitions.tf
  tests/deployment/lib/archetype_definitions/archetype_definition_customer_online.json
  tests/deployment/lib/archetype_definitions/archetype_definition_customer_root.json
  tests/deployment/resources.tf
Labels: enhancement

#50 Add code review workflow and fix linting issues
  .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1
  .github/scripts/Invoke-LibraryUpdate.ps1
  .github/workflows/code-review.yml
  .github/workflows/update-policy.yml
  README.md
  main.tf
  tests/deployment/main.tf
  tests/scripts/azp-strategy.ps1
  tests/scripts/azp-strategy.sh
  tests/scripts/tf-apply.sh
  tests/scripts/tf-destroy.sh
  tests/scripts/tf-init.sh
  tests/scripts/tf-install.sh
  tests/scripts/tf-plan.sh
  tests/scripts/tf-prepare.sh
Labels: enhancement

#54 Patch Role Assignments
  locals.policy_assignments.tf
Labels: bug

#57 Adds required_providers configuration block
  terraform.tf
Labels: enhancement

#62 Perform input validation on all custom landing zone keys
  variables.tf
Labels: enhancement

#64 Patch Policy Issues
  .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1
  locals.policy_assignments.tf
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json
  modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deny_publicendpoints.tmpl.json
  modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diag_loganalytics.tmpl.json
  modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_sql_security.tmpl.json
  modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_enforce_encrypttransit.tmpl.json
  modules/archetypes/locals.policy_definitions.tf
  modules/archetypes/locals.policy_set_definitions.tf
Labels: bug, enhancement
