Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2022-12, with the labels that each got.

#532 Update MCSB policy assignment
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json
  tests/modules/test_001_baseline/baseline_values.json
  tests/modules/test_002_add_custom_core/baseline_values.json
  tests/modules/test_003_add_mgmt_conn/baseline_values.json
Labels: enhancement

#541 Revert `Update Library Templates` workflow to use schedule
  .github/workflows/update-policy.yml
Labels: enhancement

#547 Fix managed parameters used for the `Deploy-Private-DNS-Zones` Policy Assignment
  RELEASE.md
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_private_dns_zones.tmpl.json
  modules/connectivity/locals.tf
  tests/modules/settings/settings.connectivity.tf
  tests/modules/test_002_add_custom_core/baseline_values.json
  tests/modules/test_003_add_mgmt_conn/baseline_values.json
Labels: bug

#558 Add new connectivity capabilities
  RELEASE.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
  docs/wiki/[User-Guide]-Module-Variables.md
  docs/wiki/[Variables]-configure_connectivity_resources.md
  docs/wiki/[Variables]-configure_connectivity_resources.settings.dns.md
  docs/wiki/[Variables]-configure_connectivity_resources.settings.vwan_hub_networks.md
  locals.tf
  modules/connectivity/locals.tf
  modules/connectivity/variables.tf
  outputs.tf
  tests/modules/settings/settings.connectivity.tf
  variables.tf
Labels: bug, enhancement

#560 Update DNS for Azure Batch
  RELEASE.md
  modules/connectivity/locals.tf
  tests/modules/test_002_add_custom_core/baseline_values.json
  tests/modules/test_003_add_mgmt_conn/baseline_values.json
Labels: bug

#561 Update `optional()` defaults
  RELEASE.md
  docs/wiki/[Variables]-configure_connectivity_resources.md
  docs/wiki/[Variables]-configure_connectivity_resources.settings.hub_networks.md
  docs/wiki/[Variables]-configure_connectivity_resources.settings.vwan_hub_networks.md
  modules/connectivity/locals.tf
  modules/connectivity/variables.tf
  variables.tf
Labels: bug

#565 Add is it maintained badges
  README.md
Labels: documentation

#566 Add modularity example to Wiki
  RELEASE.md
  docs/caf-enterprise-scale.diagrams.vsdx
  docs/wiki/Examples.md
  docs/wiki/User-Guide.md
  docs/wiki/Video-guides.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Identity-Resources.md
  docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-orchestration.md
  docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-remote-state.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[Examples]-Override-Module-Role-Assignments.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  docs/wiki/[Variables]-create_duration_delay.md
  docs/wiki/[Variables]-custom_policy_roles.md
  docs/wiki/[Variables]-default_location.md
  docs/wiki/[Variables]-deploy_core_landing_zones.md
  docs/wiki/[Variables]-library_path.md
  docs/wiki/[Variables]-root_id.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/400-multi-module-orchestration-composition.png
  docs/wiki/media/400-multi-module-remote-state-composition.png
  examples/400-multi-with-orchestration/main.tf
  examples/400-multi-with-orchestration/modules/connectivity/main.tf
  examples/400-multi-with-orchestration/modules/connectivity/outputs.tf
  examples/400-multi-with-orchestration/modules/connectivity/settings.connectivity.tf
  examples/400-multi-with-orchestration/modules/connectivity/variables.tf
  examples/400-multi-with-orchestration/modules/core/lib/archetype_definition_customer_online.json
  examples/400-multi-with-orchestration/modules/core/main.tf
  examples/400-multi-with-orchestration/modules/core/settings.core.tf
  examples/400-multi-with-orchestration/modules/core/settings.identity.tf
  examples/400-multi-with-orchestration/modules/core/variables.tf
  examples/400-multi-with-orchestration/modules/management/main.tf
  examples/400-multi-with-orchestration/modules/management/outputs.tf
  examples/400-multi-with-orchestration/modules/management/settings.management.tf
  examples/400-multi-with-orchestration/modules/management/variables.tf
  examples/400-multi-with-orchestration/variables.tf
  examples/400-multi-with-remote-state/connectivity/main.tf
  examples/400-multi-with-remote-state/connectivity/outputs.tf
  examples/400-multi-with-remote-state/connectivity/settings.connectivity.tf
  examples/400-multi-with-remote-state/connectivity/variables.tf
  examples/400-multi-with-remote-state/core/lib/archetype_definition_customer_online.json
  examples/400-multi-with-remote-state/core/main.tf
  examples/400-multi-with-remote-state/core/remote.tf
  examples/400-multi-with-remote-state/core/settings.core.tf
  examples/400-multi-with-remote-state/core/settings.identity.tf
  examples/400-multi-with-remote-state/core/variables.tf
  examples/400-multi-with-remote-state/management/main.tf
  examples/400-multi-with-remote-state/management/outputs.tf
  examples/400-multi-with-remote-state/management/settings.management.tf
  examples/400-multi-with-remote-state/management/variables.tf
Labels: documentation

#568 Add new attributes for management resources
  RELEASE.md
  modules/management/locals.tf
  resources.management.tf
Labels: enhancement

#569 Disable DDoS protection by default
  docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-orchestration.md
  docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-remote-state.md
  examples/400-multi-with-orchestration/variables.tf
  examples/400-multi-with-remote-state/connectivity/variables.tf
Labels: enhancement

#571 Update FAQ page
  RELEASE.md
  docs/wiki/Frequently-Asked-Questions.md
Labels: documentation

#578 Fixes for issue #577
  README.md
  RELEASE.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Identity-Resources.md
  docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
  docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-orchestration.md
  docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-remote-state.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[Examples]-Override-Module-Role-Assignments.md
  docs/wiki/[User-Guide]-Getting-Started.md
  docs/wiki/[User-Guide]-Module-upgrade-guidance.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  docs/wiki/[Variables]-configure_connectivity_resources.md
  docs/wiki/[Variables]-configure_connectivity_resources.settings.hub_networks.md
  examples/400-multi-with-orchestration/modules/connectivity/main.tf
  examples/400-multi-with-orchestration/modules/core/main.tf
  examples/400-multi-with-orchestration/modules/management/main.tf
  examples/400-multi-with-remote-state/connectivity/main.tf
  examples/400-multi-with-remote-state/core/main.tf
  examples/400-multi-with-remote-state/management/main.tf
  locals.version.tf
  modules/connectivity/locals.tf
  modules/connectivity/variables.tf
  tests/modules/settings/settings.connectivity.tf
  variables.tf
Labels: bug
