Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2022-11, with the labels that each got.

#501 Pin ADO sync to `v1.1.4`
  .github/workflows/gh-ado-sync.yml
Labels: bug

#509 Fixed revoke_certificate variable iterator
  resources.connectivity.tf
Labels: bug

#516 Update firewall configuration options
  README.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Identity-Resources.md
  docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[Examples]-Override-Module-Role-Assignments.md
  docs/wiki/[User-Guide]-Getting-Started.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  modules/connectivity/locals.tf
  modules/role_assignments_for_policy/terraform.tf
  resources.connectivity.tf
  terraform.tf
  tests/README.md
  tests/modules/settings/settings.connectivity.tf
  tests/modules/test_001_baseline/terraform.tf
  tests/modules/test_002_add_custom_core/terraform.tf
  tests/modules/test_003_add_mgmt_conn/baseline_values.json
  tests/modules/test_003_add_mgmt_conn/terraform.tf
  tests/opa/policy/readme.md
  tests/scripts/azp-strategy.ps1
Labels: bug, enhancement

#522 Add updated upgrade guidance to Wiki
  RELEASE.md
  docs/wiki/[User-Guide]-Module-Releases.md
  docs/wiki/[User-Guide]-Module-upgrade-guidance.md
  docs/wiki/[User-Guide]-Upgrade-from-v2.4.1-to-v3.0.0.md
  docs/wiki/[User-Guide]-Upgrade-guides.md
  docs/wiki/_Sidebar.md
Labels: documentation

#526 Update private DNS zones
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
  docs/wiki/[User-Guide]-Module-Variables.md
  docs/wiki/[User-Guide]-Upgrade-from-v2.4.1-to-v3.0.0.md
  docs/wiki/[Variables]-configure_connectivity_resources.md
  docs/wiki/[Variables]-configure_connectivity_resources.settings.dns.md
  modules/connectivity/locals.tf
  modules/connectivity/variables.tf
  tests/modules/settings/settings.connectivity.tf
  tests/modules/test_003_add_mgmt_conn/baseline_values.json
  variables.tf
Labels: enhancement

#529 Add Kubernetes namespace for Arc DNS
  RELEASE.md
  modules/connectivity/locals.tf
Labels: bug

#530 Add link to Upgrade to v3.0.0 guide
  README.md
Labels: documentation
