Repository Azure/terraform-azurerm-caf-enterprise-scale, pull requests merged in 2022-03, with the labels that each got.

#286 Add `Edit-LineEndings` to simplify local running
  .gitattributes
  .gitconfig
  .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1
  .github/scripts/Invoke-LibraryUpdate.ps1
Labels: enhancement

#289 Wiki doc for how to create Custom Policy, Policy Sets and assign them
  README.md
  docs/wiki/[Examples]-Create-Custom-Policies-Policy-Sets-and-Assignments.md
  docs/wiki/_Sidebar.md
Labels: documentation, enhancement

#294 Add FabricBot Config-as-Code
  .github/fabricbot.json
Labels: enhancement

#296 Add Missing Databricks Default Policy Assignments to Corp MG to Match ALZ Accelerator Experience
  modules/archetypes/lib/archetype_definitions/archetype_definition_es_corp.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_databricks_public_ip.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_databricks_sku.tmpl.json
  modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_databricks_vnet.tmpl.json
Labels: enhancement

#312 Release 1.1.4
  README.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
  docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Default-Configuration.md
  docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
  docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Identity-Resources.md
  docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
  docs/wiki/[Examples]-Deploy-Management-Resources.md
  docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
  docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
  docs/wiki/[Examples]-Override-Module-Role-Assignments.md
  docs/wiki/[User-Guide]-Getting-Started.md
  docs/wiki/[User-Guide]-Provider-Configuration.md
  locals.tf
  terraform.tf
  tests/scripts/azp-strategy.ps1
Labels: bug
